### ISSUE TITLE
Can't run wokd

### ISSUE THREAD

**Issue by DocMAX** [kimchi-project/wok#245]
```
Traceback (most recent call last):
  File "/usr/bin/wokd", line 30, in <module>
    import wok.server
  File "/usr/lib/python2.7/site-packages/wok/server.py", line 23, in <module>
    import cherrypy
  File "/usr/lib/python2.7/site-packages/cherrypy/__init__.py", line 76, in <module>
    from . import _cprequest, _cpserver, _cptree, _cplogging, _cpconfig
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpserver.py", line 8, in <module>
    from cherrypy.process.servers import ServerAdapter
  File "/usr/lib/python2.7/site-packages/cherrypy/process/__init__.py", line 14, in <module>
    from . import plugins, servers
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 126, in <module>
    import portend
  File "/usr/lib/python2.7/site-packages/portend.py", line 18, in <module>
    from tempora import timing
  File "/usr/lib/python2.7/site-packages/tempora/timing.py", line 137, in <module>
    class BackoffDelay(six.Iterator):
  File "/usr/lib/python2.7/site-packages/tempora/timing.py", line 225, in BackoffDelay
    @jaraco.functools.save_method_args
AttributeError: 'module' object has no attribute 'save_method_args'

```

**Comment by chr0mag** [comment]
This is seen on Archlinux after upgrading from _python2-tempora_ to 1.13-1 . Downgrading to 1.12-1 works around this for now.

**Comment by DocMAX** [comment]
thank you, it works with the downgrade

**Comment by chr0mag** [comment]
I'd leave this open actually. The downgrade is only a workaround. A modification to support the updated package is still in order.
